FROM golang:1.8

RUN apt-get update -qq && apt-get upgrade -y && \
    apt-get install -y postgresql-client sqlite3

RUN go get -v -u github.com/gobuffalo/buffalo/buffalo

COPY . /go/src/github.com/bitrise-io/addons-firebase-testlab-android/
RUN cd /go/src/github.com/bitrise-io/addons-firebase-testlab-android/ && \
    go install -v
