FROM golang:1.11

RUN apt-get update -qq && apt-get upgrade -y && \
    apt-get install -y postgresql-client sqlite3

RUN go get -v -u github.com/gobuffalo/buffalo/buffalo
RUN go get -v -u github.com/gobuffalo/buffalo-pop

COPY . /go/src/github.com/bitrise-io/addons-firebase-testlab/
RUN cd /go/src/github.com/bitrise-io/addons-firebase-testlab/ && \
    go install -v
